[code]#include <iostream>

void swap (int& a, int& b);

int main (int argc, char** argv){
	int n = 32;
	int m = 64;
	std::cout << "n = " << n << std::endl << "m = " << m << std::endl;
	std::cout << std::endl << "Swapping n & m..." << std::endl << std::endl;
	swap (n,m);
	std::cout << "n = " << n << std::endl << "m = " << m << std::endl;
	return 0;
}

void swap (int& a, int& b){
	int c = a;
	a = b;
	b = c;
	return;
}
[/code]